name: &name "TitaNet-Finetune"
sample_rate: &sample_rate 16000

init_from_nemo_model:
  lang_id_task:
    path: /models/ambernet.nemo
    # name: 'titanet_large'
    include: ["preprocessor","encoder"]
    exclude: ["decoder.final"] # Add specific layer names here to exlude or just ["decoder"] if to exclude all of decoder pretrained weights

model:
  train_ds:
    manifest_filepath: /datasets/mms_lid/train_split/train_manifest.json
    labels: null
    sample_rate: 16000
    batch_size: 8 # 16
    shuffle: true
    is_tarred: false
    tarred_audio_filepaths: null
    tarred_shard_strategy: "scatter"
    num_workers: 8
    min_duration: 1.0
    random_chunk: false
    random_chunk_len: 5.0
    augmentor:
      speed:
        prob: 0.3
        sr: *sample_rate
        resample_type: 'kaiser_fast'
        min_speed_rate: 0.95
        max_speed_rate: 1.05

  validation_ds:
    manifest_filepath: /datasets/mms_lid/dev_split/dev_manifest.json
    labels: null
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8

  test_ds:
    manifest_filepath: /datasets/mms_lid/test_split/test_manifest.json
    labels: null
    sample_rate: 16000
    batch_size: 4
    num_workers: 8

  model_defaults:
    filters: 1024
    repeat: 3
    dropout: 0.1
    separable: true
    se: true
    se_context_size: -1
    kernel_size_factor: 1.0
    
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: "per_feature"
    window_size: 0.025
    sample_rate: *sample_rate
    window_stride: 0.01
    window: "hann"
    features: &n_mels 80
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001

  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    feat_in: *n_mels
    activation: relu
    conv_mask: true

    jasper:
      -   filters: ${model.model_defaults.filters}
          repeat: 1
          kernel: [3]
          stride: [1]
          dilation: [1]
          dropout: 0.0
          residual: false
          separable: ${model.model_defaults.separable}
          se: ${model.model_defaults.se}
          se_context_size: ${model.model_defaults.se_context_size}

      -   filters: ${model.model_defaults.filters}
          repeat:  ${model.model_defaults.repeat}
          kernel: [7]
          stride: [1]
          dilation: [1]
          dropout: ${model.model_defaults.dropout}
          residual: true
          separable: ${model.model_defaults.separable}
          se: ${model.model_defaults.se}
          se_context_size: ${model.model_defaults.se_context_size}

      -   filters: ${model.model_defaults.filters}
          repeat: ${model.model_defaults.repeat}
          kernel: [11]
          stride: [1]
          dilation: [1]
          dropout: ${model.model_defaults.dropout}
          residual: true
          separable: ${model.model_defaults.separable}
          se: ${model.model_defaults.se}
          se_context_size: ${model.model_defaults.se_context_size}

      -   filters: ${model.model_defaults.filters}
          repeat: ${model.model_defaults.repeat}
          kernel: [15]
          stride: [1]
          dilation: [1]
          dropout: ${model.model_defaults.dropout}
          residual: true
          separable: ${model.model_defaults.separable}
          se: ${model.model_defaults.se}
          se_context_size: ${model.model_defaults.se_context_size}

      -   filters: &enc_feat_out 3072
          repeat: 1
          kernel: [1]
          stride: [1]
          dilation: [1]
          dropout: 0.0
          residual: false
          separable: ${model.model_defaults.separable}
          se: ${model.model_defaults.se}
          se_context_size: ${model.model_defaults.se_context_size}

  decoder:
    _target_: nemo.collections.asr.modules.SpeakerDecoder
    feat_in: *enc_feat_out
    num_classes: 3
    pool_mode: 'attention'
    emb_sizes: 192

  loss:
    _target_: nemo.collections.asr.losses.angularloss.AngularSoftmaxLoss # you could also use cross-entrophy loss
    scale: 30
    margin: 0.2

  optim_param_groups:
    encoder:
      lr: 1e-04 #.001

  optim:
    name: adamw
    lr: 5e-05 # .0001 #(original titanet-large was trained with 0.08 lr)
    weight_decay: 0.0002

    # scheduler setup
    # sched:
    #   name: CosineAnnealing
    #   warmup_ratio: 0.1
    #   min_lr: 0.0
    # sched:
    #   name: PolynomialHoldDecayAnnealing # <--- Use this scheduler
    #   warmup_ratio: 0.1                  # <--- Fraction of total steps for warmup
    #   hold_ratio: 0.4                    # <--- Fraction of total steps to hold at peak LR
    #   power: 1.0                         # <--- Power of the polynomial decay (1.0 is linear decay)
    #   min_lr: 0.0   
    sched:
      name: ReduceLROnPlateau # <--- Use this scheduler name
      monitor: 'val_loss'     # <--- Metric name to monitor (MUST match your validation logging)
      mode: 'min'             # <--- 'min' if monitoring loss, 'max' if monitoring accuracy/score
      factor: 0.1             # <--- Factor by which the learning rate will be reduced (new_lr = old_lr * factor)
      patience: 3             # <--- Number of validation epochs with no improvement after which LR will be reduced
      min_lr: 1e-05 

trainer:
  devices: 1 # number of gpus (original titanet-large was trained on 4 nodes with 8 gpus each)
  max_epochs: 40
  max_steps: -1 # computed at runtime if not set
  num_nodes: 1
  accelerator: gpu
  strategy: ddp
  deterministic: True
  enable_checkpointing: False
  logger: False
  log_every_n_steps: 1  # Interval of logging.
  val_check_interval: 1.0  # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
  gradient_clip_val: 1.0

exp_manager:
  exp_dir: /models/nemo_test
  name: *name
  create_tensorboard_logger: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: 'val_loss' # Metric to monitor for saving
    mode: 'min'         # 'min' or 'max'
    save_top_k: 3       # Save the single best model
    save_last: True     # Also save the last model (optional)
    # every_n_epochs: 1 # Save every N epochs regardless of performance (optional)
    # every_n_train_steps: null # Save every N steps regardless of performance (optional)
    verbose: True # The schema default is True

  # # This flag controls the automatic creation of the early stopping callback
  # create_early_stopping_callback: True

  # # All early stopping parameters go under this key:
  # early_stopping_callback_params:
  #   monitor: 'val_loss' # Must match the metric name monitored for checkpointing
  #   mode: 'min'         # 'min' for loss, 'max' for accuracy/score
  #   patience: 5        # Number of validation epochs to wait for improvement
  #   min_delta: 0.001    # Minimum change to qualify as improvement (optional)
  #   verbose: True      # Whether to print messages (schema default is True)

  resume_from_checkpoint: null
  # resume_from_checkpoint: /models/nemo_test/TitaNet-Finetune/2025-04-30_07-26-58-ReduceLROnPlateau-no-ES/checkpoints/TitaNet-Finetune--val_loss=1.2359-epoch=38-last.ckpt